# Generated by Django 5.2.17 on 2026-09-15 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Request categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="This person is the 'Department Manager' approver for requests from this department.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalWorkflowRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "min_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave empty for 'and above'.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="When several rules match, the highest priority (larger number) wins.",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty to apply to all departments.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.department",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty to apply to all categories.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.requestcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "min_amount"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalStepRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="1 = first approver, 2 = second, ..."
                    ),
                ),
                (
                    "approver_role",
                    models.CharField(
                        choices=[
                            ("DEPARTMENT_MANAGER", "Department Manager"),
                            ("FINANCE", "Finance"),
                            ("SENIOR_MANAGER", "Senior Manager / Director"),
                            ("SPECIFIC_USER", "Specific person"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "specific_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only used when 'approver role' is 'Specific person'.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="core.approvalworkflowrule",
                    ),
                ),
            ],
            options={
                "ordering": ["workflow_rule", "order"],
                "unique_together": {("workflow_rule", "order")},
            },
        ),
    ]
