# Generated by Django 5.2.17 on 2026-09-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approvalsteprule",
            options={
                "ordering": ["workflow_rule", "order"],
                "verbose_name": "დამტკიცების საფეხური",
                "verbose_name_plural": "დამტკიცების საფეხურები",
            },
        ),
        migrations.AlterModelOptions(
            name="approvalworkflowrule",
            options={
                "ordering": ["-priority", "min_amount"],
                "verbose_name": "დამტკიცების წესი",
                "verbose_name_plural": "დამტკიცების წესები",
            },
        ),
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["name"],
                "verbose_name": "დეპარტამენტი",
                "verbose_name_plural": "დეპარტამენტები",
            },
        ),
        migrations.AlterModelOptions(
            name="requestcategory",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "კატეგორია",
                "verbose_name_plural": "მოთხოვნის კატეგორიები",
            },
        ),
        migrations.AlterField(
            model_name="approvalsteprule",
            name="approver_role",
            field=models.CharField(
                choices=[
                    ("DEPARTMENT_MANAGER", "დეპარტამენტის მენეჯერი"),
                    ("FINANCE", "ფინანსები"),
                    ("SENIOR_MANAGER", "უფროსი მენეჯერი / დირექტორი"),
                    ("SPECIFIC_USER", "კონკრეტული პირი"),
                ],
                max_length=32,
            ),
        ),
    ]
