# Generated by Django 5.2.17 on 2026-09-19 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_approvalsteprule_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalsteprule",
            name="approver_role",
            field=models.CharField(
                choices=[
                    ("DEPARTMENT_MANAGER", "დეპარტამენტის დირექტორი"),
                    ("FINANCE", "ფინანსები"),
                    ("SENIOR_MANAGER", "კომპანიის დირექტორი"),
                    ("SPECIFIC_USER", "კონკრეტული პირი"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="ეს პირია ამ დეპარტამენტის 'დეპარტამენტის დირექტორი' — ამტკიცებს ამ დეპარტამენტის მოთხოვნებს (თუ თავად არის მომთხოვნელი, ეს საფეხური ავტომატურად გამოტოვდება).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_departments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
