# Generated by Django 5.2.17 on 2026-09-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_approvalsteprule_approver_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalsteprule",
            name="approver_role",
            field=models.CharField(
                choices=[
                    ("DEPARTMENT_MANAGER", "დეპარტამენტის დირექტორი"),
                    ("PROCUREMENT_MANAGER", "შესყიდვების მენეჯერი"),
                    ("FINANCE", "ფინანსები"),
                    ("SENIOR_MANAGER", "კომპანიის დირექტორი"),
                    ("SPECIFIC_USER", "კონკრეტული პირი"),
                ],
                max_length=32,
            ),
        ),
    ]
