# Generated by Django 5.2.17 on 2026-09-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestapproval",
            name="approver_role",
            field=models.CharField(
                choices=[
                    ("DEPARTMENT_MANAGER", "Department Manager"),
                    ("FINANCE", "Finance"),
                    ("SENIOR_MANAGER", "Senior Manager / Director"),
                    ("SPECIFIC_USER", "Specific person"),
                ],
                max_length=32,
            ),
        ),
    ]
