# Generated by Django 5.2.17 on 2026-09-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0002_alter_requestapproval_approver_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestapproval",
            name="decision",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("INFO_REQUESTED", "More Information Requested"),
                    ("SKIPPED", "Skipped"),
                ],
                default="NOT_STARTED",
                max_length=16,
            ),
        ),
    ]
