# Generated by Django 5.2.17 on 2026-09-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0003_alter_requestapproval_decision"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentdetail",
            options={
                "verbose_name": "გადახდის დეტალი",
                "verbose_name_plural": "გადახდის დეტალები",
            },
        ),
        migrations.AlterModelOptions(
            name="request",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "მოთხოვნა",
                "verbose_name_plural": "მოთხოვნები",
            },
        ),
        migrations.AlterModelOptions(
            name="requestapproval",
            options={
                "ordering": ["request", "step_order"],
                "verbose_name": "დამტკიცების საფეხური",
                "verbose_name_plural": "დამტკიცების ისტორია",
            },
        ),
        migrations.AlterModelOptions(
            name="requestattachment",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "დანართი",
                "verbose_name_plural": "დანართები",
            },
        ),
        migrations.AlterModelOptions(
            name="requestcomment",
            options={
                "ordering": ["created_at"],
                "verbose_name": "კომენტარი",
                "verbose_name_plural": "კომენტარები",
            },
        ),
        migrations.AlterField(
            model_name="request",
            name="priority",
            field=models.CharField(
                choices=[
                    ("LOW", "დაბალი"),
                    ("MEDIUM", "საშუალო"),
                    ("HIGH", "მაღალი"),
                    ("URGENT", "სასწრაფო"),
                ],
                default="MEDIUM",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("PURCHASE", "შესყიდვა"),
                    ("SERVICE", "სერვისი"),
                    ("SUBSCRIPTION", "გამოწერა / პროგრამული უზრუნველყოფა"),
                    ("REPAIR_MAINTENANCE", "შეკეთება / ტექმომსახურება"),
                    ("OTHER", "სხვა"),
                ],
                default="PURCHASE",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "მონახაზი"),
                    ("SUBMITTED", "გაგზავნილი"),
                    ("PENDING_MANAGER_APPROVAL", "მენეჯერის დამტკიცების მოლოდინში"),
                    ("MORE_INFO_REQUIRED", "საჭიროა დამატებითი ინფორმაცია"),
                    ("MANAGER_APPROVED", "მენეჯერმა დაამტკიცა"),
                    ("PENDING_FINANCE_REVIEW", "ფინანსების განხილვის მოლოდინში"),
                    (
                        "PENDING_SENIOR_APPROVAL",
                        "უფროსი მენეჯმენტის დამტკიცების მოლოდინში",
                    ),
                    ("APPROVED", "დამტკიცებული"),
                    ("REJECTED", "უარყოფილი"),
                    ("PURCHASE_IN_PROGRESS", "შესყიდვა მიმდინარეობს"),
                    ("PURCHASED", "შეძენილი"),
                    ("PAID", "გადახდილი"),
                    ("COMPLETED", "დასრულებული"),
                    ("CANCELLED", "გაუქმებული"),
                ],
                default="DRAFT",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="requestapproval",
            name="approver_role",
            field=models.CharField(
                choices=[
                    ("DEPARTMENT_MANAGER", "დეპარტამენტის მენეჯერი"),
                    ("FINANCE", "ფინანსები"),
                    ("SENIOR_MANAGER", "უფროსი მენეჯერი / დირექტორი"),
                    ("SPECIFIC_USER", "კონკრეტული პირი"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="requestapproval",
            name="decision",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "არ დაწყებულა"),
                    ("PENDING", "მოლოდინში"),
                    ("APPROVED", "დამტკიცებული"),
                    ("REJECTED", "უარყოფილი"),
                    ("INFO_REQUESTED", "მოთხოვნილია დამატებითი ინფორმაცია"),
                    ("SKIPPED", "გამოტოვებული"),
                ],
                default="NOT_STARTED",
                max_length=16,
            ),
        ),
    ]
