# Generated by Django 5.2.17 on 2026-09-19 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_approvalsteprule_approver_role_and_more"),
        (
            "requests_app",
            "0004_alter_paymentdetail_options_alter_request_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="ცარიელი დატოვება შესაძლებელია კომპანიის დირექტორისა და სხვა კომპანიის მასშტაბის როლებისთვის.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requests",
                to="core.department",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "მონახაზი"),
                    ("SUBMITTED", "გაგზავნილი"),
                    (
                        "PENDING_MANAGER_APPROVAL",
                        "დეპარტამენტის დირექტორის დამტკიცების მოლოდინში",
                    ),
                    ("MORE_INFO_REQUIRED", "საჭიროა დამატებითი ინფორმაცია"),
                    ("MANAGER_APPROVED", "დეპარტამენტის დირექტორმა დაამტკიცა"),
                    ("PENDING_FINANCE_REVIEW", "ფინანსების განხილვის მოლოდინში"),
                    (
                        "PENDING_SENIOR_APPROVAL",
                        "კომპანიის დირექტორის დამტკიცების მოლოდინში",
                    ),
                    ("APPROVED", "დამტკიცებული"),
                    ("REJECTED", "უარყოფილი"),
                    ("PURCHASE_IN_PROGRESS", "შესყიდვა მიმდინარეობს"),
                    ("PURCHASED", "შეძენილი"),
                    ("PAID", "გადახდილი"),
                    ("COMPLETED", "დასრულებული"),
                    ("CANCELLED", "გაუქმებული"),
                ],
                default="DRAFT",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="requestapproval",
            name="approver_role",
            field=models.CharField(
                choices=[
                    ("DEPARTMENT_MANAGER", "დეპარტამენტის დირექტორი"),
                    ("FINANCE", "ფინანსები"),
                    ("SENIOR_MANAGER", "კომპანიის დირექტორი"),
                    ("SPECIFIC_USER", "კონკრეტული პირი"),
                ],
                max_length=32,
            ),
        ),
    ]
