# Generated by Django 5.2.17 on 2026-09-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests_app", "0005_alter_request_department_alter_request_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "მონახაზი"),
                    ("SUBMITTED", "გაგზავნილი"),
                    (
                        "PENDING_MANAGER_APPROVAL",
                        "დეპარტამენტის დირექტორის დამტკიცების მოლოდინში",
                    ),
                    (
                        "PENDING_PROCUREMENT_REVIEW",
                        "შესყიდვების მენეჯერის დამუშავების მოლოდინში",
                    ),
                    ("MORE_INFO_REQUIRED", "საჭიროა დამატებითი ინფორმაცია"),
                    ("MANAGER_APPROVED", "დეპარტამენტის დირექტორმა დაამტკიცა"),
                    ("PENDING_FINANCE_REVIEW", "ფინანსების განხილვის მოლოდინში"),
                    (
                        "PENDING_SENIOR_APPROVAL",
                        "კომპანიის დირექტორის დამტკიცების მოლოდინში",
                    ),
                    ("APPROVED", "დამტკიცებული"),
                    ("REJECTED", "უარყოფილი"),
                    ("PURCHASE_IN_PROGRESS", "შესყიდვა მიმდინარეობს"),
                    ("PURCHASED", "შეძენილი"),
                    ("PAID", "გადახდილი"),
                    ("COMPLETED", "დასრულებული"),
                    ("CANCELLED", "გაუქმებული"),
                ],
                default="DRAFT",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="requestapproval",
            name="approver_role",
            field=models.CharField(
                choices=[
                    ("DEPARTMENT_MANAGER", "დეპარტამენტის დირექტორი"),
                    ("PROCUREMENT_MANAGER", "შესყიდვების მენეჯერი"),
                    ("FINANCE", "ფინანსები"),
                    ("SENIOR_MANAGER", "კომპანიის დირექტორი"),
                    ("SPECIFIC_USER", "კონკრეტული პირი"),
                ],
                max_length=32,
            ),
        ),
    ]
